
# Configuración Estética Nurture (Claro)
allow_remote_control yes
listen_on unix:@mykitty

# Fuente
font_family       JetBrainsMono Nerd Font Mono
font_size         13.0

# Transparencia

dynamic_background_opacity yes

# Colores

# Cursor
cursor                #dc8a78
cursor_text_color     #ff5eb3

#margen interno
window_padding_width 14

# Bordes de Ventana Kitty (Si abres más de una)
active_border_color   #40a02b
inactive_border_color #bcc0cc

# Paleta de Colores de la Terminal 
# vim:ft=kitty

## name:     Catppuccin Kitty Diff Latte
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/diff-latte.conf
## blurb:    Soothing pastel theme for the high-spirited!
# --- Nurture Y2K Pastel Refinado (Intensidad Ajustada) ---

# Texto y Fondo (Gris carbón suave para máxima legibilidad)
foreground       #3f444a
background       #eff1f5
background_opacity    0.85
selection_foreground #3f444a
selection_background #d2dbf4

# Cursor (Rosa pastel vibrante)
cursor           #f4b8e4
cursor_text_color #ffffff

# --- Los 16 Colores de la Terminal ---

# Negro / Gris base
color0 #52616f
color8 #708190

# Rojo -> El Rosa Sakura que te encantó (Subido un pelín para que resalte)
color1 #f29ec2
color9 #fbcce6

# Verde -> ¡Tu verde de referencia perfecto!
color2  #82b76f
color10 #a1cb92

# Amarillo -> Crema Ocre / Miel Suave
color3  #e1b878
color11 #f1d399

# Azul -> Azul Denim / Cielo de Tarde
color4  #7ba3cc
color12 #9cbce2

# Magenta -> Lila / Lavanda Intenso
color5  #bfa1b8
color13 #dbbdd4

# Cian -> Aqua Intenso / Menta Y2K
color6  #7ec4cf
color14 #aae0e7

# Blanco / Gris claro
color7  #d1d7e0
color15 #ebf0f6

#background_opacity    0.45
startup_session launch zsh -c "fastfetch; zsh"
